#!/usr/bin/env python3
"""Sync the vendored WorkBuddy tree with upstream workbuddy2api-panel.

internal/workbuddy is generated by vendor_workbuddy.py, but the committed tree
also carries afree-local hand edits (PoolEnabled switch, models stale-snapshot
replay, taskcenter tweaks). A plain re-vendor would wipe them. This script
replays the manual procedure safely:

  base   = vendor(upstream baseline commit)   pristine vendor output
  ours   = current internal/workbuddy         base + local hand edits
  theirs = vendor(upstream HEAD)              new upstream + script rewrites

Every file is three-way merged with `git merge-file`: local hand edits survive,
upstream changes flow in, genuine collisions are left as <<<<<<< markers and
the baseline is NOT advanced until they are resolved and --seal is run.
Upstream itself is never written to (only `--pull` runs a ff-only pull there).

Usage:
  python scripts/sync_workbuddy.py             # merge upstream into the tree
  python scripts/sync_workbuddy.py --report    # show what would change, write nothing
  python scripts/sync_workbuddy.py --pull      # ff-only pull upstream first
  python scripts/sync_workbuddy.py --source D:/path/to/workbuddy2api-panel
  python scripts/sync_workbuddy.py --seal      # after resolving conflicts, record baseline
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
from datetime import datetime
from io import BytesIO
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
ROOT = SCRIPTS.parent
WB_PKG = ROOT / "internal" / "workbuddy"
BASELINE_FILE = SCRIPTS / "workbuddy-vendor-baseline.json"

sys.path.insert(0, str(SCRIPTS))
import vendor_workbuddy as V  # noqa: E402


def git(source: Path, *args: str) -> str:
    r = subprocess.run(["git", "-C", str(source), *args],
                       capture_output=True, text=True, encoding="utf-8", errors="replace")
    if r.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)}: {r.stderr.strip()}")
    return r.stdout


def upstream_head(source: Path) -> str:
    return git(source, "rev-parse", "HEAD").strip()


def upstream_dirty(source: Path) -> bool:
    return bool(git(source, "status", "--porcelain").strip())


def upstream_version(source: Path) -> str:
    main_go = source / "cmd" / "server" / "main.go"
    if not main_go.is_file():
        return "?"
    m = re.search(r'appVersion\s*=\s*"([^"]+)"', main_go.read_text(encoding="utf-8"))
    return m.group(1) if m else "?"


def local_version() -> str:
    wb_go = ROOT / "internal" / "app" / "workbuddy.go"
    m = re.search(r'workbuddyVersion\s*=\s*"([^"]+)"', wb_go.read_text(encoding="utf-8"))
    return m.group(1) if m else "?"


def load_baseline() -> dict:
    if not BASELINE_FILE.is_file():
        sys.exit(f"缺少基线文件 {BASELINE_FILE}。\n"
                 "若当前 internal/workbuddy 恰好是上游 HEAD 的纯净 vendor 产物（无手工改动），"
                 "运行 --seal 登记基线；否则无法确定合并 base，请人工处理。")
    return json.loads(BASELINE_FILE.read_text(encoding="utf-8"))


def save_baseline(source: Path, commit: str) -> None:
    BASELINE_FILE.write_text(json.dumps({
        "commit": commit,
        "synced_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "upstream_version": upstream_version(source),
    }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def archive_commit(source: Path, commit: str, dest: Path) -> None:
    raw = subprocess.run(["git", "-C", str(source), "archive", "--format=tar",
                          commit, "internal", "cmd/server"],
                         capture_output=True, check=True).stdout
    with tarfile.open(fileobj=BytesIO(raw)) as tf:
        try:
            tf.extractall(dest, filter="data")
        except TypeError:  # Python < 3.12 has no filter kwarg
            tf.extractall(dest)


def rel_files(root: Path) -> dict[str, Path]:
    out: dict[str, Path] = {}
    for p in root.rglob("*"):
        if p.is_file():
            out[p.relative_to(root).as_posix()] = p
    return out


def read_lf(p: Path) -> bytes:
    # Working-tree files may be CRLF (autocrlf checkout) while vendor output is
    # LF; the committed blobs are LF, so normalize all merge inputs — otherwise
    # every line of "ours" differs and merge-file degrades to whole-file conflicts.
    return p.read_bytes().replace(b"\r\n", b"\n")


def merge_file(theirs: bytes, base: bytes, ours: bytes, tmp: Path) -> tuple[bytes, int]:
    """Three-way merge of LF-normalized inputs; returns (merged bytes, conflicts)."""
    cur, bp, op = tmp / "mf-cur", tmp / "mf-base", tmp / "mf-ours"
    cur.write_bytes(theirs)
    bp.write_bytes(base)
    op.write_bytes(ours)
    r = subprocess.run(["git", "merge-file", "-L", "OURS", "-L", "BASE", "-L", "THEIRS",
                        str(cur), str(bp), str(op)],
                       capture_output=True, text=True)
    if r.returncode < 0:
        raise RuntimeError(f"git merge-file: {r.stderr.strip()}")
    return cur.read_bytes(), r.returncode


def conflict_markers() -> list[str]:
    return sorted(rel for rel, p in rel_files(WB_PKG).items()
                  if p.suffix in V.ASSET_SUFFIXES and b"<<<<<<< " in p.read_bytes())


def cmd_seal(source: Path) -> int:
    if upstream_dirty(source):
        print("上游工作区不干净，拒绝登记基线。", file=sys.stderr)
        return 1
    marked = conflict_markers()
    if marked:
        print("树内仍有冲突标记，先解决再 --seal：", file=sys.stderr)
        for rel in marked:
            print(f"  {rel}", file=sys.stderr)
        return 1
    head = upstream_head(source)
    save_baseline(source, head)
    print(f"基线已登记: {head[:12]} (上游 {upstream_version(source)})")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="上游 WorkBuddy 更新同步（vendor + 三方合并）")
    ap.add_argument("--source", help="上游仓库路径（默认取 vendor_workbuddy.SOURCE_ROOT）")
    ap.add_argument("--pull", action="store_true", help="先对上游执行 git pull --ff-only")
    ap.add_argument("--report", action="store_true", help="只显示将发生的变更，不写任何文件")
    ap.add_argument("--seal", action="store_true", help="解决冲突后把上游 HEAD 登记为新基线")
    args = ap.parse_args()

    src = Path(args.source) if args.source else V.SOURCE_ROOT
    if not (src / "internal").is_dir():
        print(f"上游仓库不存在或缺少 internal/: {src}", file=sys.stderr)
        return 1
    if args.seal:
        return cmd_seal(src)

    baseline = load_baseline()
    base_commit = baseline["commit"]
    if upstream_dirty(src):
        print("上游工作区不干净（只读原则：不信任未提交内容，也不修改上游），先在上游提交或还原。",
              file=sys.stderr)
        return 1
    if args.pull:
        print(git(src, "pull", "--ff-only").strip())
    head = upstream_head(src)
    if head == base_commit:
        print(f"上游无新提交（基线 {base_commit[:12]}，版本 {baseline.get('upstream_version', '?')}）")
        return 0

    print(f"=== 上游新提交（{base_commit[:12]}..{head[:12]}，{upstream_version(src)}）===")
    print(git(src, "log", "--oneline", f"{base_commit}..HEAD").rstrip())
    stat = git(src, "diff", "--stat", f"{base_commit}..HEAD").rstrip()
    print(stat)
    print()

    tmp = Path(tempfile.mkdtemp(prefix="wb-sync-"))
    try:
        base_src = tmp / "base-src"
        base_out = tmp / "base"
        theirs_out = tmp / "theirs"
        archive_commit(src, base_commit, base_src)
        for source, target in ((base_src, base_out), (src, theirs_out)):
            if V.main(source_root=source, target_root=target, preserve_from=WB_PKG) != 0:
                print("vendor 构建失败（原因见上方 stderr：可能是改写锚点随上游结构失效），"
                      "修 scripts/vendor_workbuddy.py 后重试。", file=sys.stderr)
                return 1

        ours = rel_files(WB_PKG)
        base = rel_files(base_out / "internal" / "workbuddy")
        theirs = rel_files(theirs_out / "internal" / "workbuddy")

        merges: list[tuple[str, bytes, int]] = []   # (rel, merged bytes, conflicts)
        upstream_new: list[str] = []
        upstream_gone: list[str] = []               # 上游删除：警告并保留本地
        locally_deleted: list[str] = []             # 本地删除：跳过不复活
        for rel in sorted(set(theirs) | set(ours)):
            t, o, b = theirs.get(rel), ours.get(rel), base.get(rel)
            if t and o and b:
                t_data, o_data = read_lf(t), read_lf(o)
                if t_data == o_data:
                    continue  # 上游未动，且与当前一致
                data, n = merge_file(t_data, read_lf(b), o_data, tmp)
                merges.append((rel, data, n))
            elif t and not o and not b:
                upstream_new.append(rel)
            elif t and not o and b:
                locally_deleted.append(rel)
            elif not t and o and b:
                upstream_gone.append(rel)
            # 其余（仅本地有/仅本地删）= 本地自治，保留不动。

        if args.report:
            would = sum(1 for _, _, n in merges if n == 0)
            bad = [(rel, n) for rel, _, n in merges if n]
            print(f"[report] 将合并 {len(merges)} 个文件（直接 {would}，冲突 {len(bad)}），"
                  f"上游新增 {len(upstream_new)}，上游删除 {len(upstream_gone)}，本地已删 {len(locally_deleted)}")
            for rel, n in bad:
                print(f"  冲突({n}): {rel}")
            for rel in upstream_new:
                print(f"  上游新增: {rel}")
            for rel in upstream_gone:
                print(f"  上游删除(本地保留): {rel}")
            print("[report] 未写任何文件。")
            return 0

        for rel, data, _ in merges:
            target = WB_PKG / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
        for rel in upstream_new:
            target = WB_PKG / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(theirs[rel].read_bytes())

        clean = [(rel, n) for rel, _, n in merges if n == 0]
        bad = [(rel, n) for rel, _, n in merges if n]
        print(f"合并完成: 干净 {len(clean)} / 冲突 {len(bad)} / 上游新增 {len(upstream_new)}")
        for rel in upstream_new:
            print(f"  上游新增: {rel}")
        for rel in locally_deleted:
            print(f"  跳过（本地已删，上游仍有）: {rel}")
        for rel in upstream_gone:
            print(f"  警告（上游已删，本地保留待人工判断）: {rel}")
        if bad:
            print("\n存在冲突，解决 <<<<<<< 标记后运行: python scripts/sync_workbuddy.py --seal")
            for rel, n in bad:
                print(f"  冲突({n}): {rel}")
            return 1

        save_baseline(src, head)
        print(f"基线已推进: {head[:12]} (上游 {upstream_version(src)})")
        if local_version().removesuffix("+afree") != upstream_version(src):
            print(f"提醒: 本地 workbuddyVersion={local_version()}，上游 appVersion={upstream_version(src)}，"
                  "请同步 internal/app/workbuddy.go 的版本号。")
        print("\n后续人工步骤（脚本无法代劳）:")
        print("  1. internal/app/workbuddy.go + workbuddy_config.go: 新配置键/新模块的装配与热应用、")
        print("     restartRequired 清单、版本号 workbuddyVersion")
        print("  2. 验证: docker run --rm -v \"D:/下载/Github/afree-proxy:/build\" -w /build \\")
        print("         afree-proxy:workbuddy-builder sh -c 'go build ./... && go vet ./internal/... \\")
        print("         && go test ./internal/app/ ./internal/workbuddy/...'")
        print("     (-race 需先在容器内 apk add --no-cache gcc musl-dev)")
        print("  3. git add -A && git commit")
        return 0
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
